### ISSUE TITLE
Relation Attention和GAT的关系？？？为什么模型中用的都是Relation Attention，而没有用GAT？

### ISSUE THREAD

**Issue by 2274900** [shenwzh3/RGAT-ABSA#11]
请教一个问题：
在你的论文中，提到了这篇文章的GAT的缺陷，然后你提出了RGAT，是GAT再用额外的relational heads组合而成，但是在你的代码中，model里的的模型都没有用model_gcn中的GAT模型，input的输入中adj都没有构建，只用了relation attention。您的模型确实取得了不错的结果，但是仿佛和GAT并没有多大关系？是我理解错了吗？求告知

**Comment by sha-lala** [comment]
我是刚入坑的，我也有这样的疑问？
