### ISSUE TITLE
你好，我对你的研究工作非常感兴趣，我想问下你这个实验具体参数要怎么设置，因为我根据你提供的参数跑的精确度差了3个多点，能帮忙解答一下吗，谢谢

### ISSUE THREAD

**Issue by julin1991** [shenwzh3/RGAT-ABSA#2]

**Comment by shenwzh3** [comment]
repo中提供的参数是我们在本地设备中利用grid search获得的最优超参数，但是由于该数据集的测试集并非使用线上打榜，所以不同实验环境（设备、cuda版本、torch版本）都会对实验结果造成一定影响，另外这个数据集的测试集样本数较少，误差会更明显，我想这是所有深度学习相关研究都会遇到的问题。

**Comment by julin1991** [comment]
非常谢谢你的解释！
