### ISSUE TITLE
可以给一下bert和glove两个开源的url吗，我在导入过程中显示导入失败

### ISSUE THREAD

**Issue by hangjiaqi1** [shenwzh3/RGAT-ABSA#7]
我下载的bert的文件结构
-uncased_L-12_H-768_A-12
--bert_model.ckpt.data-00000-of-00001
--bert_model.ckpt.index
--bert_model.ckpt.meta
--config.json
--vocab.txt

报错日志
OSError: Can't load config for '/data/uncased_L-12_H-768_A-12'. Make sure that:

- '/data/uncased_L-12_H-768_A-12' is a correct model identifier listed on 'https://huggingface.co/models'

- or '/data/uncased_L-12_H-768_A-12' is the correct path to a directory containing a config.json file

parse设置地址
    parser.add_argument('--bert_model_dir', type=str, default='/data/uncased_L-12_H-768_A-12',
                        help='Path to pre-trained Bert model.')
run.sh
python run.py --gat_bert --embedding_type bert --output_dir data/output-gcn --dropout 0.3 --hidden_size 200 --learning_rate 5e-5 #R-GAT+BERT in restaurant

可能就是我文件没下对，可以给个url吗(•̀へ•╮)

**Comment by shenwzh3** [comment]
你下载的这个是tf版本的bert模型权重，你要下载pytorch版本的模型权重，可以按照报错日志在https://huggingface.co/models这个链接下载

**Comment by hangjiaqi1** [comment]
> 你下载的这个是tf版本的bert模型权重，你要下载pytorch版本的模型权重，可以按照报错日志在[https://huggingface.co/models这个链接下载](https://huggingface.co/models%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E4%B8%8B%E8%BD%BD)

谢谢
